version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: denis_fill_db  # ${POSTGRES_DB}
      POSTGRES_USER: postgres  # ${POSTGRES_USER}
      POSTGRES_PASSWORD: 58796  # ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data